#es用户名 密码等配置
elasticsearch:
  host: ${eshost}
  username: ${esusername}
  password: ${espassword}
  port: ${esport}

#openEuler    openGauss    openLookeng    mindSpore
system: ${searchsystem:openEuler}

#formal test
dep: ${depp:test}

api:
  allApi:
  sigNameApi:
  sigReadmeApi:
  repoInfoApi:

server:
  port: 8080